trigger:
- main

pr: none
pool:
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: "Build"
  displayName: Build
  jobs:
  - job: "Build"
    displayName: Build
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: DockerImageBuild
  displayName: DockerImageBuild
  dependsOn: "Build"
  jobs:
  - job: DockerImageBuild
    displayName: DockerImageBuild
    steps:
    - checkout: none
    - task: CmdLine@2
      inputs:
        script: |
          docker system prune -f --all
          docker build -t devopsagentcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId) -f Dockerfile-Project-1 .
          trivy image --exit-code 0 --severity MEDIUM,HIGH devopsagentcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
          #trivy image --exit-code 1 --severity CRITICAL devopsagentcontainer24registry.azurecr.io/samplewebapp:$(Build.BuildId)
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker-Registry'
        repository: 'samplewebapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile-Project-1'
- stage: AzureContainerAppDeploymentusingTerraform
  displayName: AzureContainerAppDeploymentusingTerraform
  dependsOn: DockerImageBuild
  jobs:
  - deployment: AzureContainerAppDeploymentusingTerraform
    displayName: AzureContainerAppDeploymentusingTerraform
    environment: "prod"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                git clone https://$(GIT_USERNAME):$(GIT_PASSWORD)@github.com/singhritesh85/DevOps-Project-Docker-the-Serverless-way.git
                cd opentofu-azure-container-app-appgtw-bankapp-mysql-flexible-servers/main
                tofu init
                tofu plan -var certificate_password=$(certificate_password) -var SERVER_ACR=$(SERVER_ACR) -var REPO_NAME="samplewebapp" -var TAG_NUMBER=$(Build.BuildId)
                tofu apply -auto-approve -var certificate_password=$(certificate_password) -var SERVER_ACR=$(SERVER_ACR) -var REPO_NAME="samplewebapp" -var TAG_NUMBER=$(Build.BuildId) 
      